index:
    pattern:  /
    defaults: { _controller: ZestfuleBlogBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: ZestfuleUserBundle:Security:login }

login_check:
    pattern: /login_check