## Security Configuration
security:
    encoders:
        Zestfule\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: Zestfule\UserBundle\Entity\User, property: id }

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login

    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }